### ISSUE TITLE
Add serializers for interaction with DRF

### ISSUE THREAD

**Issue by rixx** [raphaelm/django-i18nfield#10]
`djangorestframework` is an exceedingly common framework to help Django applications that want to provide an API. Having an easy way of serialization of I18nStrings (for example like pretix has) would be nice.

**Comment by raphaelm** [comment]
Good point! Do you think the serializers from pretix are reusable enough to just port them over here?

**Comment by rixx** [comment]
That was my thought, yes. Let me go if I can help out.

**Comment by raphaelm** [comment]
Sure, if you want, create a PR to move them here, otherwise I'll put it somewhere on my list :)
