### ISSUE TITLE
Docs online?

### ISSUE THREAD

**Issue by jedie** [raphaelm/django-i18nfield#16]
I found https://github.com/raphaelm/django-i18nfield/tree/master/docs
Are the docs online readable somewhere?

**Comment by raphaelm** [comment]
Yes, here: https://django-i18nfield.readthedocs.io/en/latest/ :)

**Comment by jedie** [comment]
Ah, thanks! I didn't saw the link in the github project description. I only looked into the README... No i see, that the "docs passing" is also a link...

**Comment by raphaelm** [comment]
> Ah, thanks! I didn't saw the link in the github project description.

Well, I just added it in there when I saw your ticket :P
