### ISSUE TITLE
Do not show flags if only one locale is given

### ISSUE THREAD

**Issue by rixx** [raphaelm/django-i18nfield#23]
I'd like not to show a confusing flag in case only one locale is available on an i18nfield. Is that something you'd consider adding, either generally or behind a widget flag (sic!)?

**Comment by raphaelm** [comment]
I'd consider adding it generally, the flag really does not make much sense in this case.

**Comment by raphaelm** [comment]
However, I would not want to remove the ``lang`` attribute from fields in this case, since it may be useful for browsers (spellchecking etc). So we'd need to maybe add a class to the surrounding div to make this accessible in CSS?
