### ISSUE TITLE
Using "manage.py dumpdata", only one language is exported

### ISSUE THREAD

**Issue by mol-lux** [raphaelm/django-i18nfield#26]
Hello,

I was trying to migrate data from one instance of my app to another using `manage.py dumpdata` and `manage.py loaddata`. However, only one single locale made it to the other end.
Upon further investigation, I see that the generated fixture only contains the data in one single locale, which leads me to conclude that `manage.py dumpdata` simply evaluates the model field's contents. which I18nField then returns as a string in a single language.

Is there any other way for migrating data from one application to another? Or is it better to just dump the data from the database and reload it into the new one?

**Comment by raphaelm** [comment]
This is probably a bug, unfortunately I do not have time to look into it at the moment
